"""init

Revision ID: 422e7a47abd3
Revises: dede0dbbb165
Create Date: 2025-09-11 15:43:05.332389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "422e7a47abd3"
down_revision: Union[str, Sequence[str], None] = "dede0dbbb165"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "embd_lrn", sa.Column("recipient_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "embd_lrn", sa.Column("recipient_email", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embd_lrn", "recipient_email")
    op.drop_column("embd_lrn", "recipient_name")
    # ### end Alembic commands ###
