"""init

Revision ID: dede0dbbb165
Revises: 5422f4bd6192
Create Date: 2025-09-08 01:08:15.693695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dede0dbbb165"
down_revision: Union[str, Sequence[str], None] = "5422f4bd6192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ics_file_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("disposition", sa.String(length=127), nullable=True),
        sa.Column("method", sa.String(length=127), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embd_lrn_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["embd_lrn_id"], ["embd_lrn.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ics_file_data_embd_lrn_id"),
        "ics_file_data",
        ["embd_lrn_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ics_file_data_embd_lrn_id"), table_name="ics_file_data")
    op.drop_table("ics_file_data")
    # ### end Alembic commands ###
