"""init

Revision ID: 78e876e2d357
Revises:
Create Date: 2025-09-08 12:47:03.039406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "78e876e2d357"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "salary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("amount_from", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("amount_to", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "(amount_from IS NULL) OR (amount_to IS NULL) OR (amount_to >= amount_from)",
            name="ck_salary_amount_from_non_bigger_than_amount_to",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("employment_type", sa.String(length=64), nullable=False),
        sa.Column("work_mode", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("applied_email_received", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_email_id", sa.Integer(), nullable=True),
        sa.Column("denied_email_received", sa.DateTime(timezone=True), nullable=True),
        sa.Column("denied_email_id", sa.Integer(), nullable=True),
        sa.Column(
            "meeting_inv_email_received", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("meeting_inv_email_id", sa.Integer(), nullable=True),
        sa.Column(
            "meeting_crt_email_received", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("meeting_crt_email_id", sa.Integer(), nullable=True),
        sa.Column(
            "meeting_upd_email_received", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("meeting_upd_email_id", sa.Integer(), nullable=True),
        sa.Column(
            "meeting_cncl_email_received", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("meeting_cncl_email_id", sa.Integer(), nullable=True),
        sa.Column("salary_applied_id", sa.Integer(), nullable=True),
        sa.Column("salary_proposed_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["salary_applied_id"], ["salary.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["salary_proposed_id"], ["salary.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("row_id"),
    )
    op.create_index(
        op.f("ix_application_salary_applied_id"),
        "application",
        ["salary_applied_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_salary_proposed_id"),
        "application",
        ["salary_proposed_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_salary_proposed_id"), table_name="application")
    op.drop_index(op.f("ix_application_salary_applied_id"), table_name="application")
    op.drop_table("application")
    op.drop_table("salary")
    # ### end Alembic commands ###
