# Docker commands

docker-image-build:
	docker build -t hire_insight_ai_assistant_mail_tracker:latest .
	minikube image load hire_insight_ai_assistant_mail_tracker:latest

docker-image-rm:
	docker image rm hire_insight_ai_assistant_mail_tracker:latest
