# Docker commands

docker-image-build:
	docker build -t hire_insight_ai_assistant_telegram_bot:latest .
	minikube image load hire_insight_ai_assistant_telegram_bot:latest

docker-image-rm:
	docker image rm hire_insight_ai_assistant_telegram_bot:latest
